Added color configuration to each of the cells
paulrolfe/PARTagPicker pull request #21
Opened 2016-11-17 15:48 UTC by mtgomes

Using the same strategy as the global colouring, added PARTag that contains the title and the color definition. This will allow for, each of the labels, to have their own color scheme. 

Updated the example to reflect this and added some commented code to better display the different cases.

2016-11-17 17:10 UTC, paulrolfe commented
Thanks, this looks great at first glance. I should have time to review it more thoroughly later today.

2016-11-17 17:42 UTC, mtgomes commented
No worries. I'm a Swift guy so apologies for the potential mistakes.

2016-11-17 20:27 UTC, paulrolfe requested changes
Yeah, I've been out of Obj-C for a while myself.

Overall I'm just concerned with not breaking this library for people already interacting with it via strings. So a lot of my suggestions are around that. Unfortunately it will be impossible to keep all interactions the same when using these new tags. 

For instance, using my suggestions, when you access the tag picker's `chosenTags` array after a delegate callback, it's going to be an array of `PARTags` now. I'd love to find a solution for that as well. It might mean tracking the tags with some internal variable and leaving `chosenTags` with whatever types it was set to externally. 

I still need to think on that problem a little.

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/PARTagPickerViewController.h
> +@property (nonatomic, strong) NSMutableArray<PARTag *> *chosenTags;
For backwards compatibility, I'd like leave this without the generics. Objective-C users would be fine, but swift users would be confined to passing in PARTags's I believe. So, I'd like consumers of this library to still be able to pass in strings, without creating a `PARTag`.

Then in the setter in the implementation we can turn each object into a PARTag if it's not already one.

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/PARTagPickerViewController.h
> +@property (nonatomic, strong) NSArray<PARTag *> *allTags;
For backwards compatibility, I'd like leave this without the generics. Objective-C users would be fine, but swift users would be confined to passing in PARTags's I believe. So, I'd like consumers of this library to still be able to pass in strings, without creating a `PARTag`.

Then in the setter in the implementation we can turn each object into a PARTag if it's not already one.

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/Tag/PARTag+Comparison.h
> +- (PARTag *)similarStringFromArray:(NSArray<PARTag *> *)strings;
Shouldn't this be called `(PARTag *)similarTagFromArray:(NSArray<PARTag *> *)tags;`

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/ViewController.m
> +
Add a comment that everything below here is an example for using PARTags instead of just NSString

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/ViewController.m
> +- (PARTagColorReference *)useCustomColors {
I'm fine with this, but rename to just `customColors`

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/main.m
> + //
Extra space

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/Tag/PARTag.h
> +@property (nonatomic, strong) PARTagColorReference *colorReference;
Can you tag this with `_nullable`?

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/PARTagPickerViewController.m
> +- (PARTag *)tagSimilarToTag:(NSString *)tag {
Should be `tagSimilarToString: (NSString *)string`

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/PARTagPickerViewController.m
> +            PARTag *possibleMatch = [self tagSimilarToTag:tag];
This is actually a comment about line 409: we should call variable `tag` something like `tagString` now.

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/Tag/PARTag+Comparison.m
> +- (PARTag *)similarStringFromArray:(NSArray<PARTag *> *)strings{
`- (PARTag *)similarTagFromArray:(NSArray<PARTag *> *)tags { ... }`

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/Tag/PARTag.m
> +        //self.colorReference = [[PARTagColorReference alloc] initWithDefaultColors];
delete line

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/ViewController.m
> +    __weak ViewController *weakSelf = self;
This isn't being used, I think we should remove it.

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/ViewController.m
> +    //self.tagPicker.tagColorRef = myColors;
delete commented line

2016-11-17 20:27 UTC, paulrolfe commented on README.md
> +The tags are passed in as `PARTag` objects in an array. Anytime you change the `allTags` array, any existing `chosenTags` are updated to use references to the new objects if they contain a match in t
... passed in as `PARTag` or `NSString` objects...

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/PARTagPickerViewController.m
> +        //cell.tagColorRef = self.tagColorRef;
remove commented line

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/PARTagPickerViewController.h
>   *  Array of strings.
Array of `NSString`s or `PARTag`s

2016-11-17 20:27 UTC, paulrolfe commented on PARTagPicker/Classes/PARTagPickerViewController.h
> +@property (nonatomic, strong) NSArray<PARTag *> *allTags;
Those setters would then look something like:
```
- (void)setAllTags:(NSArray *)allTags {
    NSArray<PARTag *> *convertedTags = [self convertToTagObjects: allTags];
    _allTags = convertedTags;
    self.availableTags = [_allTags mutableCopy];
    [self transferChosenTagsWithNewAllTags];
    [self.availableTags removeObjectsInArray: _chosenTags];
    [self filterTagsFromSearchString];
}

- (void)setChosenTags:(NSMutableArray *)chosenTags {
    NSMutableArray<PARTag *> *convertedTags = [self convertToTagObjects: chosenTags];
    _chosenTags = convertedTags;
    [self.chosenTagCollectionView reloadData];
    self.availableTags = [_allTags mutableCopy];
    [self.availableTags removeObjectsInArray: _chosenTags];
    [self filterTagsFromSearchString];
}

- (NSMutableArray *)convertToTagObjects:(NSArray *)otherArray {
    NSMutableArray *newArray = [NSMutableArray new];
    for (id object in otherArray) {
        if ([object isKindOfClass:[PARTag class]]) {
            [newArray addObject:object];
        } else if ([object isKindOfClass:[NSString class]]) {
            PARTag *tag = [[PARTag alloc] initWithText:(NSString *)object];
            [newArray addObject:tag];
        }
    }
    return newArray;
}
```

2016-11-18 10:01 UTC, mtgomes commented on PARTagPicker/Classes/Tag/PARTag+Comparison.h
> +- (PARTag *)similarStringFromArray:(NSArray<PARTag *> *)strings;
Yep, forgot to change the name..

2016-11-18 10:02 UTC, mtgomes commented on PARTagPicker/ViewController.m
> +    __weak ViewController *weakSelf = self;
I left it because of the code inside the block, but indeed that should be commented also.

2016-11-18 10:03 UTC, mtgomes commented on PARTagPicker/Classes/PARTagPickerViewController.m
> +- (PARTag *)tagSimilarToTag:(NSString *)tag {
Exactly

2016-11-18 10:06 UTC, mtgomes commented
Good suggestions overall. In the meantime I've created another version with an ID in the tag and some other minor changes. Will integrate your comments and issue another pull request. 

I understand your concerns. Let me think about it further and comment back if I find a decent solution..

2017-02-08 05:39 UTC, paulrolfe commented
@mtgomes  I saw a notification about some new commits. You want me to take another look at this PR when I get a chance?

2023-02-08 09:19 UTC, closed without merging